modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/DoctorFTB/SkipEnchants/issues"
[[mods]]
modId="skip_enchants"
version="${file.jarVersion}"
displayName="Skip Enchants"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skip-enchants"
authors="FTB_lag"
description='''
Have a bad enchants in table? Just skip it!
'''
